language: node_js
node_js: 8
os: linux
install:
  - npm install
cache:
  directories:
    - node_modules
jobs:
  include:
  - stage: Check
    script:
    - npm run lint-travis
  - stage: Build
    script:
    - npm run build
  - stage: Test
    script:
    - npm run test
